-- EasyHover release manifest. GENERATED by tools/gen_manifest.js -- do not edit by hand.
--
-- Read by easyhover_suite.lua over HTTPS and parsed with textutils.unserialise, so this is a
-- plain data table: no function calls, no `return`, nothing executable.
--
-- `sum` is FNV-1a 32-bit over the file's LF-normalised bytes, paired with `size`. Together they
-- answer "did this change" and "did the download arrive intact". The trust root is HTTPS to the
-- pinned raw.githubusercontent.com URL, not this checksum.
--
-- `version` is a digest of every shipped file's sum+size, so it moves only when shipped bytes
-- move. `schema` is the persisted-config generation: a bump means saved configs get backed up.
--
-- `status = "prepared"` roles are reserved in the design but ship no files yet. The Suite
-- offers them and says so rather than pretending an empty install succeeded.
{
  ["base"] = "https://raw.githubusercontent.com/maar-10/EasyHover/main",
  ["roles"] = {
    ["flight"] = {
      ["blurb"] = "Thrusters, sensors, pilot inputs, PID loops. One per craft. No UI.",
      ["configs"] = {
        "/eh_flight_config.tbl",
      },
      ["dirs"] = {
        "flight",
      },
      ["entry"] = "flight/startup.lua",
      ["files"] = {
        {
          ["dst"] = "flight/app.lua",
          ["size"] = 66359,
          ["src"] = "flight/app.lua",
          ["sum"] = "f9faac55",
        },
        {
          ["dst"] = "flight/diskmenu.lua",
          ["size"] = 5705,
          ["src"] = "flight/diskmenu.lua",
          ["sum"] = "62f6ed5a",
        },
        {
          ["dst"] = "flight/lib/config.lua",
          ["size"] = 46355,
          ["src"] = "flight/lib/config.lua",
          ["sum"] = "8caac411",
        },
        {
          ["dst"] = "flight/lib/control/altitude.lua",
          ["size"] = 12857,
          ["src"] = "flight/lib/control/altitude.lua",
          ["sum"] = "ca162cb3",
        },
        {
          ["dst"] = "flight/lib/control/assist.lua",
          ["size"] = 4272,
          ["src"] = "flight/lib/control/assist.lua",
          ["sum"] = "4fce1603",
        },
        {
          ["dst"] = "flight/lib/control/attitude.lua",
          ["size"] = 8764,
          ["src"] = "flight/lib/control/attitude.lua",
          ["sum"] = "7dd48ba5",
        },
        {
          ["dst"] = "flight/lib/control/axismap.lua",
          ["size"] = 14641,
          ["src"] = "flight/lib/control/axismap.lua",
          ["sum"] = "97c01d7f",
        },
        {
          ["dst"] = "flight/lib/control/brake.lua",
          ["size"] = 4112,
          ["src"] = "flight/lib/control/brake.lua",
          ["sum"] = "1fe4fff1",
        },
        {
          ["dst"] = "flight/lib/control/comlevel.lua",
          ["size"] = 4932,
          ["src"] = "flight/lib/control/comlevel.lua",
          ["sum"] = "df5def25",
        },
        {
          ["dst"] = "flight/lib/control/envelope.lua",
          ["size"] = 5013,
          ["src"] = "flight/lib/control/envelope.lua",
          ["sum"] = "e14c8268",
        },
        {
          ["dst"] = "flight/lib/control/filter.lua",
          ["size"] = 5337,
          ["src"] = "flight/lib/control/filter.lua",
          ["sum"] = "e8bffdf6",
        },
        {
          ["dst"] = "flight/lib/control/mixer.lua",
          ["size"] = 11210,
          ["src"] = "flight/lib/control/mixer.lua",
          ["sum"] = "eb4f3906",
        },
        {
          ["dst"] = "flight/lib/control/oscillation.lua",
          ["size"] = 4133,
          ["src"] = "flight/lib/control/oscillation.lua",
          ["sum"] = "f24faff4",
        },
        {
          ["dst"] = "flight/lib/control/pid.lua",
          ["size"] = 4538,
          ["src"] = "flight/lib/control/pid.lua",
          ["sum"] = "2bf6fd69",
        },
        {
          ["dst"] = "flight/lib/control/selftest.lua",
          ["size"] = 21435,
          ["src"] = "flight/lib/control/selftest.lua",
          ["sum"] = "db11da3e",
        },
        {
          ["dst"] = "flight/lib/input/bindings.lua",
          ["size"] = 4991,
          ["src"] = "flight/lib/input/bindings.lua",
          ["sum"] = "12c5988e",
        },
        {
          ["dst"] = "flight/lib/input/controller.lua",
          ["size"] = 3272,
          ["src"] = "flight/lib/input/controller.lua",
          ["sum"] = "bd8e465a",
        },
        {
          ["dst"] = "flight/lib/input/pilot.lua",
          ["size"] = 4088,
          ["src"] = "flight/lib/input/pilot.lua",
          ["sum"] = "e9aad15e",
        },
        {
          ["dst"] = "flight/lib/input/typewriter.lua",
          ["size"] = 4020,
          ["src"] = "flight/lib/input/typewriter.lua",
          ["sum"] = "b762d51b",
        },
        {
          ["dst"] = "flight/lib/io/disk.lua",
          ["size"] = 9573,
          ["src"] = "flight/lib/io/disk.lua",
          ["sum"] = "54a2d72d",
        },
        {
          ["dst"] = "flight/lib/io/engine.lua",
          ["size"] = 6445,
          ["src"] = "flight/lib/io/engine.lua",
          ["sum"] = "f678ee3c",
        },
        {
          ["dst"] = "flight/lib/io/fuel.lua",
          ["size"] = 9621,
          ["src"] = "flight/lib/io/fuel.lua",
          ["sum"] = "0eb88765",
        },
        {
          ["dst"] = "flight/lib/io/relays.lua",
          ["size"] = 3924,
          ["src"] = "flight/lib/io/relays.lua",
          ["sum"] = "3475cc3b",
        },
        {
          ["dst"] = "flight/lib/io/sensors.lua",
          ["size"] = 12563,
          ["src"] = "flight/lib/io/sensors.lua",
          ["sum"] = "0df3cabe",
        },
        {
          ["dst"] = "flight/lib/io/thrusters.lua",
          ["size"] = 24753,
          ["src"] = "flight/lib/io/thrusters.lua",
          ["sum"] = "a093f8bb",
        },
        {
          ["dst"] = "flight/lib/log.lua",
          ["size"] = 2780,
          ["src"] = "flight/lib/log.lua",
          ["sum"] = "9596a83a",
        },
        {
          ["dst"] = "flight/lib/modes.lua",
          ["size"] = 11525,
          ["src"] = "flight/lib/modes.lua",
          ["sum"] = "f674e850",
        },
        {
          ["dst"] = "flight/lib/peripherals.lua",
          ["size"] = 13005,
          ["src"] = "flight/lib/peripherals.lua",
          ["sum"] = "1b246235",
        },
        {
          ["dst"] = "flight/lib/state.lua",
          ["size"] = 4576,
          ["src"] = "flight/lib/state.lua",
          ["sum"] = "5d5eda8b",
        },
        {
          ["dst"] = "flight/lib/telemetry.lua",
          ["size"] = 18642,
          ["src"] = "flight/lib/telemetry.lua",
          ["sum"] = "eaf026bd",
        },
        {
          ["dst"] = "flight/lib/util.lua",
          ["size"] = 3189,
          ["src"] = "flight/lib/util.lua",
          ["sum"] = "d0b4653e",
        },
        {
          ["dst"] = "flight/startup.lua",
          ["size"] = 681,
          ["src"] = "flight/startup.lua",
          ["sum"] = "609afac6",
        },
        {
          ["dst"] = "shared/install.lua",
          ["size"] = 1978,
          ["src"] = "shared/install.lua",
          ["sum"] = "4e1b5714",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 541,
          ["src"] = "launchers/flight.lua",
          ["sum"] = "56719b25",
        },
      },
      ["luaPath"] = "/flight",
      ["status"] = "released",
      ["title"] = "Flight computer",
    },
    ["gps_beacon"] = {
      ["blurb"] = "One of four world-anchored hosts that let the craft locate itself. Answers CC's own gps.locate() pings and reports link status and constellation quality.",
      ["configs"] = {
        "/eh_gps_beacon_config.tbl",
      },
      ["dirs"] = {
        "gps_beacon",
        "shared",
      },
      ["entry"] = "gps_beacon/startup.lua",
      ["files"] = {
        {
          ["dst"] = "gps_beacon/app.lua",
          ["size"] = 7796,
          ["src"] = "gps_beacon/app.lua",
          ["sum"] = "e432de1f",
        },
        {
          ["dst"] = "gps_beacon/lib/config.lua",
          ["size"] = 4685,
          ["src"] = "gps_beacon/lib/config.lua",
          ["sum"] = "55adb091",
        },
        {
          ["dst"] = "gps_beacon/lib/geometry.lua",
          ["size"] = 6270,
          ["src"] = "gps_beacon/lib/geometry.lua",
          ["sum"] = "8f285205",
        },
        {
          ["dst"] = "gps_beacon/lib/host.lua",
          ["size"] = 6449,
          ["src"] = "gps_beacon/lib/host.lua",
          ["sum"] = "1fa715f6",
        },
        {
          ["dst"] = "gps_beacon/lib/mesh.lua",
          ["size"] = 6189,
          ["src"] = "gps_beacon/lib/mesh.lua",
          ["sum"] = "c319c501",
        },
        {
          ["dst"] = "gps_beacon/startup.lua",
          ["size"] = 514,
          ["src"] = "gps_beacon/startup.lua",
          ["sum"] = "5c2f94ce",
        },
        {
          ["dst"] = "gps_beacon/ui/console.lua",
          ["size"] = 7590,
          ["src"] = "gps_beacon/ui/console.lua",
          ["sum"] = "a81e02b3",
        },
        {
          ["dst"] = "shared/install.lua",
          ["size"] = 1978,
          ["src"] = "shared/install.lua",
          ["sum"] = "4e1b5714",
        },
        {
          ["dst"] = "shared/log.lua",
          ["size"] = 2735,
          ["src"] = "shared/log.lua",
          ["sum"] = "d5d9781f",
        },
        {
          ["dst"] = "shared/util.lua",
          ["size"] = 2152,
          ["src"] = "shared/util.lua",
          ["sum"] = "29c90f91",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 308,
          ["src"] = "launchers/gps_beacon.lua",
          ["sum"] = "a173a935",
        },
      },
      ["luaPath"] = "/gps_beacon",
      ["status"] = "released",
      ["title"] = "GPS beacon",
    },
    ["ground"] = {
      ["blurb"] = "Ender-modem telemetry receiver. Advisory only -- it can never command the craft.",
      ["configs"] = {
        "/eh_ground_config.tbl",
      },
      ["dirs"] = {
        "ground",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ground",
      ["status"] = "prepared",
      ["title"] = "Ground station",
    },
    ["music"] = {
      ["blurb"] = "Search, playlists and DFPWM streaming. Needs an external transcode service.",
      ["configs"] = {
        "/eh_music_config.tbl",
      },
      ["dirs"] = {
        "music",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/music",
      ["status"] = "prepared",
      ["title"] = "Entertainment",
    },
    ["nav"] = {
      ["blurb"] = "Position fixing over GPS, waypoints, and the fix relay onto the craft's cable. Needs an ender modem AND a wired one.",
      ["configs"] = {
        "/eh_nav_config.tbl",
        "/eh_waypoints.tbl",
        "/eh_routes.tbl",
      },
      ["dirs"] = {
        "nav",
        "shared",
      },
      ["entry"] = "nav/startup.lua",
      ["files"] = {
        {
          ["dst"] = "nav/app.lua",
          ["size"] = 22979,
          ["src"] = "nav/app.lua",
          ["sum"] = "2512cc47",
        },
        {
          ["dst"] = "nav/lib/config.lua",
          ["size"] = 7864,
          ["src"] = "nav/lib/config.lua",
          ["sum"] = "d81a5fcb",
        },
        {
          ["dst"] = "nav/lib/disk.lua",
          ["size"] = 4780,
          ["src"] = "nav/lib/disk.lua",
          ["sum"] = "93099c3c",
        },
        {
          ["dst"] = "nav/lib/fix.lua",
          ["size"] = 7189,
          ["src"] = "nav/lib/fix.lua",
          ["sum"] = "c57c7330",
        },
        {
          ["dst"] = "nav/lib/geo.lua",
          ["size"] = 5588,
          ["src"] = "nav/lib/geo.lua",
          ["sum"] = "c7353e5a",
        },
        {
          ["dst"] = "nav/lib/heading.lua",
          ["size"] = 8501,
          ["src"] = "nav/lib/heading.lua",
          ["sum"] = "e911889b",
        },
        {
          ["dst"] = "nav/lib/navcommand.lua",
          ["size"] = 3317,
          ["src"] = "nav/lib/navcommand.lua",
          ["sum"] = "4b0a0668",
        },
        {
          ["dst"] = "nav/lib/navtable.lua",
          ["size"] = 3093,
          ["src"] = "nav/lib/navtable.lua",
          ["sum"] = "378ecbaa",
        },
        {
          ["dst"] = "nav/lib/relay.lua",
          ["size"] = 4882,
          ["src"] = "nav/lib/relay.lua",
          ["sum"] = "967aee01",
        },
        {
          ["dst"] = "nav/lib/sources.lua",
          ["size"] = 4165,
          ["src"] = "nav/lib/sources.lua",
          ["sum"] = "681106f0",
        },
        {
          ["dst"] = "nav/lib/waypoints.lua",
          ["size"] = 8156,
          ["src"] = "nav/lib/waypoints.lua",
          ["sum"] = "c112eab9",
        },
        {
          ["dst"] = "nav/startup.lua",
          ["size"] = 510,
          ["src"] = "nav/startup.lua",
          ["sum"] = "bbf402d4",
        },
        {
          ["dst"] = "nav/ui/console.lua",
          ["size"] = 8894,
          ["src"] = "nav/ui/console.lua",
          ["sum"] = "7a0cc35d",
        },
        {
          ["dst"] = "shared/install.lua",
          ["size"] = 1978,
          ["src"] = "shared/install.lua",
          ["sum"] = "4e1b5714",
        },
        {
          ["dst"] = "shared/log.lua",
          ["size"] = 2735,
          ["src"] = "shared/log.lua",
          ["sum"] = "d5d9781f",
        },
        {
          ["dst"] = "shared/util.lua",
          ["size"] = 2152,
          ["src"] = "shared/util.lua",
          ["sum"] = "29c90f91",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 294,
          ["src"] = "launchers/nav.lua",
          ["sum"] = "1d99eddd",
        },
      },
      ["luaPath"] = "/nav",
      ["status"] = "released",
      ["title"] = "Navigation computer",
    },
    ["ui_aux"] = {
      ["blurb"] = "Lights, doors, landing gear via redstone relays.",
      ["configs"] = {
        "/eh_ui_aux_config.tbl",
      },
      ["dirs"] = {
        "ui_aux",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_aux",
      ["status"] = "prepared",
      ["title"] = "Aux control",
    },
    ["ui_main"] = {
      ["blurb"] = "Overhead engine + fuel panel and the configuration screens. Drives every assigned monitor.",
      ["configs"] = {
        "/eh_ui_main_config.tbl",
      },
      ["dirs"] = {
        "ui_main",
        "shared",
      },
      ["entry"] = "ui_main/startup.lua",
      ["files"] = {
        {
          ["dst"] = "basalt.lua",
          ["size"] = 305968,
          ["src"] = "vendor/basalt-full.lua",
          ["sum"] = "96ae5255",
        },
        {
          ["dst"] = "shared/install.lua",
          ["size"] = 1978,
          ["src"] = "shared/install.lua",
          ["sum"] = "4e1b5714",
        },
        {
          ["dst"] = "shared/log.lua",
          ["size"] = 2735,
          ["src"] = "shared/log.lua",
          ["sum"] = "d5d9781f",
        },
        {
          ["dst"] = "shared/util.lua",
          ["size"] = 2152,
          ["src"] = "shared/util.lua",
          ["sum"] = "29c90f91",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 296,
          ["src"] = "launchers/ui_main.lua",
          ["sum"] = "862bb917",
        },
        {
          ["dst"] = "ui_main/app.lua",
          ["size"] = 14805,
          ["src"] = "ui_main/app.lua",
          ["sum"] = "a7eb87c3",
        },
        {
          ["dst"] = "ui_main/lib/config.lua",
          ["size"] = 9994,
          ["src"] = "ui_main/lib/config.lua",
          ["sum"] = "50af65f3",
        },
        {
          ["dst"] = "ui_main/lib/link.lua",
          ["size"] = 8353,
          ["src"] = "ui_main/lib/link.lua",
          ["sum"] = "049a1ac0",
        },
        {
          ["dst"] = "ui_main/lib/monitors.lua",
          ["size"] = 7206,
          ["src"] = "ui_main/lib/monitors.lua",
          ["sum"] = "2b9dfbb5",
        },
        {
          ["dst"] = "ui_main/startup.lua",
          ["size"] = 634,
          ["src"] = "ui_main/startup.lua",
          ["sum"] = "47bf3c83",
        },
        {
          ["dst"] = "ui_main/ui/config_panel.lua",
          ["size"] = 39129,
          ["src"] = "ui_main/ui/config_panel.lua",
          ["sum"] = "c37cad63",
        },
        {
          ["dst"] = "ui_main/ui/nav.lua",
          ["size"] = 46188,
          ["src"] = "ui_main/ui/nav.lua",
          ["sum"] = "745276b9",
        },
        {
          ["dst"] = "ui_main/ui/overhead.lua",
          ["size"] = 10172,
          ["src"] = "ui_main/ui/overhead.lua",
          ["sum"] = "5393eb6c",
        },
        {
          ["dst"] = "ui_main/ui/slots.lua",
          ["size"] = 8377,
          ["src"] = "ui_main/ui/slots.lua",
          ["sum"] = "9c78b6b2",
        },
        {
          ["dst"] = "ui_main/ui/terminal.lua",
          ["size"] = 6289,
          ["src"] = "ui_main/ui/terminal.lua",
          ["sum"] = "fa18bab6",
        },
        {
          ["dst"] = "ui_main/ui/theme.lua",
          ["size"] = 6074,
          ["src"] = "ui_main/ui/theme.lua",
          ["sum"] = "4049fcd6",
        },
      },
      ["luaPath"] = "/ui_main",
      ["status"] = "released",
      ["title"] = "Main display",
    },
    ["ui_pfd"] = {
      ["blurb"] = "Attitude and flight-path indicator. Its own computer so the refresh rate is free.",
      ["configs"] = {
        "/eh_ui_pfd_config.tbl",
      },
      ["dirs"] = {
        "ui_pfd",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_pfd",
      ["status"] = "prepared",
      ["title"] = "Primary flight display",
    },
    ["ui_prox"] = {
      ["blurb"] = "Laser proximity warnings per vehicle surface.",
      ["configs"] = {
        "/eh_ui_prox_config.tbl",
      },
      ["dirs"] = {
        "ui_prox",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_prox",
      ["status"] = "prepared",
      ["title"] = "Proximity display",
    },
  },
  ["schema"] = 1,
  ["updater"] = {
    ["size"] = 37557,
    ["sum"] = "e26e319d",
  },
  ["version"] = "09ea5205",
}
