-- EasyHover release manifest. GENERATED by tools/gen_manifest.js -- do not edit by hand.
--
-- Read by easyhover_suite.lua over HTTPS and parsed with textutils.unserialise, so this is a
-- plain data table: no function calls, no `return`, nothing executable.
--
-- `sum` is FNV-1a 32-bit over the file's LF-normalised bytes, paired with `size`. Together they
-- answer "did this change" and "did the download arrive intact". The trust root is HTTPS to the
-- pinned raw.githubusercontent.com URL, not this checksum.
--
-- `version` is a digest of every shipped file's sum+size, so it moves only when shipped bytes
-- move. `schema` is the persisted-config generation: a bump means saved configs get backed up.
--
-- `status = "prepared"` roles are reserved in the design but ship no files yet. The Suite
-- offers them and says so rather than pretending an empty install succeeded.
{
  ["base"] = "https://raw.githubusercontent.com/maar-10/EasyHover/main",
  ["roles"] = {
    ["flight"] = {
      ["blurb"] = "Thrusters, sensors, pilot inputs, PID loops. One per craft. No UI.",
      ["configs"] = {
        "/eh_flight_config.tbl",
      },
      ["dirs"] = {
        "flight",
      },
      ["entry"] = "flight/startup.lua",
      ["files"] = {
        {
          ["dst"] = "flight/app.lua",
          ["size"] = 32344,
          ["src"] = "flight/app.lua",
          ["sum"] = "1cbcc6c4",
        },
        {
          ["dst"] = "flight/diskmenu.lua",
          ["size"] = 5705,
          ["src"] = "flight/diskmenu.lua",
          ["sum"] = "62f6ed5a",
        },
        {
          ["dst"] = "flight/lib/config.lua",
          ["size"] = 40271,
          ["src"] = "flight/lib/config.lua",
          ["sum"] = "f5fbd477",
        },
        {
          ["dst"] = "flight/lib/control/altitude.lua",
          ["size"] = 6761,
          ["src"] = "flight/lib/control/altitude.lua",
          ["sum"] = "50ea21d7",
        },
        {
          ["dst"] = "flight/lib/control/assist.lua",
          ["size"] = 4272,
          ["src"] = "flight/lib/control/assist.lua",
          ["sum"] = "4fce1603",
        },
        {
          ["dst"] = "flight/lib/control/attitude.lua",
          ["size"] = 5783,
          ["src"] = "flight/lib/control/attitude.lua",
          ["sum"] = "f42f383d",
        },
        {
          ["dst"] = "flight/lib/control/brake.lua",
          ["size"] = 4112,
          ["src"] = "flight/lib/control/brake.lua",
          ["sum"] = "1fe4fff1",
        },
        {
          ["dst"] = "flight/lib/control/envelope.lua",
          ["size"] = 5013,
          ["src"] = "flight/lib/control/envelope.lua",
          ["sum"] = "e14c8268",
        },
        {
          ["dst"] = "flight/lib/control/filter.lua",
          ["size"] = 5337,
          ["src"] = "flight/lib/control/filter.lua",
          ["sum"] = "e8bffdf6",
        },
        {
          ["dst"] = "flight/lib/control/mixer.lua",
          ["size"] = 9239,
          ["src"] = "flight/lib/control/mixer.lua",
          ["sum"] = "7b0598c0",
        },
        {
          ["dst"] = "flight/lib/control/oscillation.lua",
          ["size"] = 4133,
          ["src"] = "flight/lib/control/oscillation.lua",
          ["sum"] = "f24faff4",
        },
        {
          ["dst"] = "flight/lib/control/pid.lua",
          ["size"] = 4050,
          ["src"] = "flight/lib/control/pid.lua",
          ["sum"] = "ac177a12",
        },
        {
          ["dst"] = "flight/lib/input/bindings.lua",
          ["size"] = 4991,
          ["src"] = "flight/lib/input/bindings.lua",
          ["sum"] = "12c5988e",
        },
        {
          ["dst"] = "flight/lib/input/controller.lua",
          ["size"] = 3272,
          ["src"] = "flight/lib/input/controller.lua",
          ["sum"] = "bd8e465a",
        },
        {
          ["dst"] = "flight/lib/input/pilot.lua",
          ["size"] = 4039,
          ["src"] = "flight/lib/input/pilot.lua",
          ["sum"] = "6374388a",
        },
        {
          ["dst"] = "flight/lib/input/typewriter.lua",
          ["size"] = 3739,
          ["src"] = "flight/lib/input/typewriter.lua",
          ["sum"] = "0664ffc8",
        },
        {
          ["dst"] = "flight/lib/io/disk.lua",
          ["size"] = 9573,
          ["src"] = "flight/lib/io/disk.lua",
          ["sum"] = "54a2d72d",
        },
        {
          ["dst"] = "flight/lib/io/engine.lua",
          ["size"] = 6445,
          ["src"] = "flight/lib/io/engine.lua",
          ["sum"] = "f678ee3c",
        },
        {
          ["dst"] = "flight/lib/io/fuel.lua",
          ["size"] = 9621,
          ["src"] = "flight/lib/io/fuel.lua",
          ["sum"] = "0eb88765",
        },
        {
          ["dst"] = "flight/lib/io/relays.lua",
          ["size"] = 3924,
          ["src"] = "flight/lib/io/relays.lua",
          ["sum"] = "3475cc3b",
        },
        {
          ["dst"] = "flight/lib/io/sensors.lua",
          ["size"] = 10891,
          ["src"] = "flight/lib/io/sensors.lua",
          ["sum"] = "ac25bc22",
        },
        {
          ["dst"] = "flight/lib/io/thrusters.lua",
          ["size"] = 10500,
          ["src"] = "flight/lib/io/thrusters.lua",
          ["sum"] = "da72348e",
        },
        {
          ["dst"] = "flight/lib/log.lua",
          ["size"] = 2780,
          ["src"] = "flight/lib/log.lua",
          ["sum"] = "9596a83a",
        },
        {
          ["dst"] = "flight/lib/modes.lua",
          ["size"] = 10577,
          ["src"] = "flight/lib/modes.lua",
          ["sum"] = "b6031675",
        },
        {
          ["dst"] = "flight/lib/peripherals.lua",
          ["size"] = 13005,
          ["src"] = "flight/lib/peripherals.lua",
          ["sum"] = "1b246235",
        },
        {
          ["dst"] = "flight/lib/state.lua",
          ["size"] = 4576,
          ["src"] = "flight/lib/state.lua",
          ["sum"] = "5d5eda8b",
        },
        {
          ["dst"] = "flight/lib/telemetry.lua",
          ["size"] = 14026,
          ["src"] = "flight/lib/telemetry.lua",
          ["sum"] = "adaae864",
        },
        {
          ["dst"] = "flight/lib/util.lua",
          ["size"] = 2087,
          ["src"] = "flight/lib/util.lua",
          ["sum"] = "7e9ac342",
        },
        {
          ["dst"] = "flight/startup.lua",
          ["size"] = 681,
          ["src"] = "flight/startup.lua",
          ["sum"] = "609afac6",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 541,
          ["src"] = "launchers/flight.lua",
          ["sum"] = "56719b25",
        },
      },
      ["luaPath"] = "/flight",
      ["status"] = "released",
      ["title"] = "Flight computer",
    },
    ["ground"] = {
      ["blurb"] = "Ender-modem telemetry receiver. Advisory only -- it can never command the craft.",
      ["configs"] = {
        "/eh_ground_config.tbl",
      },
      ["dirs"] = {
        "ground",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ground",
      ["status"] = "prepared",
      ["title"] = "Ground station",
    },
    ["music"] = {
      ["blurb"] = "Search, playlists and DFPWM streaming. Needs an external transcode service.",
      ["configs"] = {
        "/eh_music_config.tbl",
      },
      ["dirs"] = {
        "music",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/music",
      ["status"] = "prepared",
      ["title"] = "Entertainment",
    },
    ["nav"] = {
      ["blurb"] = "Waypoints, routes, map UI, position fixing (GPS / radar). Feeds the flight computer.",
      ["configs"] = {
        "/eh_nav_config.tbl",
        "/eh_waypoints.tbl",
        "/eh_routes.tbl",
      },
      ["dirs"] = {
        "nav",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/nav",
      ["status"] = "prepared",
      ["title"] = "Navigation computer",
    },
    ["ui_aux"] = {
      ["blurb"] = "Lights, doors, landing gear via redstone relays.",
      ["configs"] = {
        "/eh_ui_aux_config.tbl",
      },
      ["dirs"] = {
        "ui_aux",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_aux",
      ["status"] = "prepared",
      ["title"] = "Aux control",
    },
    ["ui_main"] = {
      ["blurb"] = "Overhead engine + fuel panel and the configuration screens. Drives every assigned monitor.",
      ["configs"] = {
        "/eh_ui_main_config.tbl",
      },
      ["dirs"] = {
        "ui_main",
        "shared",
      },
      ["entry"] = "ui_main/startup.lua",
      ["files"] = {
        {
          ["dst"] = "basalt.lua",
          ["size"] = 305968,
          ["src"] = "vendor/basalt-full.lua",
          ["sum"] = "96ae5255",
        },
        {
          ["dst"] = "shared/log.lua",
          ["size"] = 2735,
          ["src"] = "shared/log.lua",
          ["sum"] = "d5d9781f",
        },
        {
          ["dst"] = "shared/util.lua",
          ["size"] = 2152,
          ["src"] = "shared/util.lua",
          ["sum"] = "29c90f91",
        },
        {
          ["dst"] = "startup.lua",
          ["size"] = 296,
          ["src"] = "launchers/ui_main.lua",
          ["sum"] = "862bb917",
        },
        {
          ["dst"] = "ui_main/app.lua",
          ["size"] = 8565,
          ["src"] = "ui_main/app.lua",
          ["sum"] = "7cd23ab5",
        },
        {
          ["dst"] = "ui_main/lib/config.lua",
          ["size"] = 6736,
          ["src"] = "ui_main/lib/config.lua",
          ["sum"] = "06c2fe16",
        },
        {
          ["dst"] = "ui_main/lib/link.lua",
          ["size"] = 4091,
          ["src"] = "ui_main/lib/link.lua",
          ["sum"] = "4079c728",
        },
        {
          ["dst"] = "ui_main/lib/monitors.lua",
          ["size"] = 7206,
          ["src"] = "ui_main/lib/monitors.lua",
          ["sum"] = "2b9dfbb5",
        },
        {
          ["dst"] = "ui_main/startup.lua",
          ["size"] = 634,
          ["src"] = "ui_main/startup.lua",
          ["sum"] = "47bf3c83",
        },
        {
          ["dst"] = "ui_main/ui/config_panel.lua",
          ["size"] = 28492,
          ["src"] = "ui_main/ui/config_panel.lua",
          ["sum"] = "90372cf3",
        },
        {
          ["dst"] = "ui_main/ui/overhead.lua",
          ["size"] = 7545,
          ["src"] = "ui_main/ui/overhead.lua",
          ["sum"] = "819ff0d4",
        },
        {
          ["dst"] = "ui_main/ui/slots.lua",
          ["size"] = 8377,
          ["src"] = "ui_main/ui/slots.lua",
          ["sum"] = "9c78b6b2",
        },
        {
          ["dst"] = "ui_main/ui/terminal.lua",
          ["size"] = 4837,
          ["src"] = "ui_main/ui/terminal.lua",
          ["sum"] = "628e710d",
        },
        {
          ["dst"] = "ui_main/ui/theme.lua",
          ["size"] = 4966,
          ["src"] = "ui_main/ui/theme.lua",
          ["sum"] = "e44d5517",
        },
      },
      ["luaPath"] = "/ui_main",
      ["status"] = "released",
      ["title"] = "Main display",
    },
    ["ui_pfd"] = {
      ["blurb"] = "Attitude and flight-path indicator. Its own computer so the refresh rate is free.",
      ["configs"] = {
        "/eh_ui_pfd_config.tbl",
      },
      ["dirs"] = {
        "ui_pfd",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_pfd",
      ["status"] = "prepared",
      ["title"] = "Primary flight display",
    },
    ["ui_prox"] = {
      ["blurb"] = "Laser proximity warnings per vehicle surface.",
      ["configs"] = {
        "/eh_ui_prox_config.tbl",
      },
      ["dirs"] = {
        "ui_prox",
      },
      ["entry"] = "",
      ["files"] = {},
      ["luaPath"] = "/ui_prox",
      ["status"] = "prepared",
      ["title"] = "Proximity display",
    },
  },
  ["schema"] = 1,
  ["updater"] = {
    ["size"] = 36872,
    ["sum"] = "305c58ce",
  },
  ["version"] = "74cf51de",
}
